### ISSUE TITLE
Lastest website build?

### ISSUE THREAD

**Issue by atharvaunde** [GDG-Ukraine/hoverboard#105]
I really liked the latest build of devfest Ukraine based on the project hoverboard.
Is the latest build (the one that is live on the website) is not available on GitHub? 
I cloned the repo but it is running devfest 2017 build. Am I missing something or am I supped to check out a specific branch?

**Comment by ozasadnyy** [comment]
@atharvaunde59 we decided to make it private, so our website will be unique by design. Please use https://github.com/gdg-x/hoverboard to make your own version
