### ISSUE TITLE
Blog posts in Firebase

### ISSUE THREAD

**Issue by Kursulla** [GDG-Ukraine/hoverboard#82]
Hi,

We are thinking to use your project for a new DevFest Berlin website, and we were thinking about a potential issue we might face:

Blog posts are left out of Firebase and for each new post we have to redeploy. So I was thinking it might be easier for non-technical persons to insert a new blog post via Firebase console

I am wondering did you face some technical constraints when trying to implement that or you just thought it should not be in Firebase for some reason?

Greetings from GDG Berlin team

**Comment by unreadablename** [comment]
Hi,
Currently we are working on storing blog posts in Firebase DB

Thank you

**Comment by Kursulla** [comment]
Perfect!!!
Do you have any idea when it might be ready?
I am asking so I know should I wait for it or should I do some work around on my own?

**Comment by ozasadnyy** [comment]
As @unreadableusername said, we are going to store almost all data in Firebase DB and storage in Hoverboard 2. Hopefully, we will release next version until the end of the summer.
Please, next time, open the issue on the original project: https://github.com/gdg-x/hoverboard

**Comment by Kursulla** [comment]
Thank you
